// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ArchivePlanData, ArchivePlanResponses, CancelSubscriptionAdminData, CancelSubscriptionAdminResponses, CancelSubscriptionData, CancelSubscriptionResponses, CheckUsageData, CheckUsageResponses, CopyPlansData, CopyPlansResponses, CreateFeatureData, CreateFeatureResponses, CreatePlanData, CreatePlanResponses, CreateSubscriptionAdminData, CreateSubscriptionAdminResponses, DeleteFeatureData, DeleteFeatureResponses, GenerateApiKeyData, GenerateApiKeyResponses, GetAnalyticsStatsData, GetAnalyticsStatsResponses, GetCreditBalanceData, GetCreditBalanceResponses, GetMyCreditsData, GetMyCreditsResponses, GetMySubscriptionData, GetMySubscriptionResponses, GetOrgAnalyticsData, GetOrgAnalyticsResponses, GetOrganizationData, GetOrganizationResponses, GetOrgModeData, GetOrgModeResponses, GetPlanData, GetPlanResponses, GetSubscriptionData, GetSubscriptionResponses, GrantCreditsData, GrantCreditsResponses, HealthCheckData, HealthCheckResponses, InvalidateOrgCacheData, InvalidateOrgCacheResponses, ListApiKeysData, ListApiKeysResponses, ListCreditTransactionsData, ListCreditTransactionsResponses, ListInvoicesData, ListInvoicesResponses, ListMyInvoicesData, ListMyInvoicesResponses, ListNetworksData, ListNetworksResponses, ListPlansData, ListPlansResponses, ListPricingData, ListPricingResponses, ListSubscriptionsData, ListSubscriptionsResponses, ListUsageEventsData, ListUsageEventsResponses, PayInvoiceData, PayInvoiceErrors, PayInvoiceResponses, ResumeSubscriptionData, ResumeSubscriptionResponses, RevokeApiKeyData, RevokeApiKeyResponses, SignInWithWalletData, SignInWithWalletResponses, SubscribeData, SubscribeErrors, SubscribeResponses, SwitchPlanData, SwitchPlanErrors, SwitchPlanResponses, TrackUsageData, TrackUsageResponses, UpdateFeatureData, UpdateFeatureResponses, UpdateOrganizationData, UpdateOrganizationResponses, UpdateOrgModeData, UpdateOrgModeResponses, UpdatePlanData, UpdatePlanResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });

/**
 * Get analytics stats
 */
export const getAnalyticsStats = <ThrowOnError extends boolean = false>(options?: Options<GetAnalyticsStatsData, ThrowOnError>) => (options?.client ?? client).get<GetAnalyticsStatsResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/analytics',
    ...options
});

/**
 * Authenticate with SIWE and get a session JWT
 */
export const signInWithWallet = <ThrowOnError extends boolean = false>(options?: Options<SignInWithWalletData, ThrowOnError>) => (options?.client ?? client).post<SignInWithWalletResponses, unknown, ThrowOnError>({ url: '/v1/auth/siwe', ...options });

/**
 * Check if a wallet can use a feature
 */
export const checkUsage = <ThrowOnError extends boolean = false>(options: Options<CheckUsageData, ThrowOnError>) => (options.client ?? client).get<CheckUsageResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/check',
    ...options
});

/**
 * Get credit balance for a wallet
 */
export const getCreditBalance = <ThrowOnError extends boolean = false>(options: Options<GetCreditBalanceData, ThrowOnError>) => (options.client ?? client).get<GetCreditBalanceResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/credits',
    ...options
});

/**
 * Grant credits to a wallet
 */
export const grantCredits = <ThrowOnError extends boolean = false>(options: Options<GrantCreditsData, ThrowOnError>) => (options.client ?? client).post<GrantCreditsResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/credits',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List credit transactions
 */
export const listCreditTransactions = <ThrowOnError extends boolean = false>(options: Options<ListCreditTransactionsData, ThrowOnError>) => (options.client ?? client).get<ListCreditTransactionsResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/credits/transactions',
    ...options
});

/**
 * List invoices
 */
export const listInvoices = <ThrowOnError extends boolean = false>(options: Options<ListInvoicesData, ThrowOnError>) => (options.client ?? client).get<ListInvoicesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/invoices',
    ...options
});

/**
 * List supported blockchain networks
 */
export const listNetworks = <ThrowOnError extends boolean = false>(options?: Options<ListNetworksData, ThrowOnError>) => (options?.client ?? client).get<ListNetworksResponses, unknown, ThrowOnError>({ url: '/v1/networks', ...options });

/**
 * Invalidate organization cache
 */
export const invalidateOrgCache = <ThrowOnError extends boolean = false>(options: Options<InvalidateOrgCacheData, ThrowOnError>) => (options.client ?? client).delete<InvalidateOrgCacheResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/organization',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get organization details
 */
export const getOrganization = <ThrowOnError extends boolean = false>(options?: Options<GetOrganizationData, ThrowOnError>) => (options?.client ?? client).get<GetOrganizationResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/organization',
    ...options
});

/**
 * Update organization
 */
export const updateOrganization = <ThrowOnError extends boolean = false>(options: Options<UpdateOrganizationData, ThrowOnError>) => (options.client ?? client).put<UpdateOrganizationResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/organization',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get detailed organization analytics
 */
export const getOrgAnalytics = <ThrowOnError extends boolean = false>(options: Options<GetOrgAnalyticsData, ThrowOnError>) => (options.client ?? client).get<GetOrgAnalyticsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/organization/analytics',
    ...options
});

/**
 * Generate a new API key
 */
export const generateApiKey = <ThrowOnError extends boolean = false>(options: Options<GenerateApiKeyData, ThrowOnError>) => (options.client ?? client).post<GenerateApiKeyResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/organization/api-key',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all active API keys
 */
export const listApiKeys = <ThrowOnError extends boolean = false>(options: Options<ListApiKeysData, ThrowOnError>) => (options.client ?? client).get<ListApiKeysResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/organization/api-keys',
    ...options
});

/**
 * Revoke an API key
 */
export const revokeApiKey = <ThrowOnError extends boolean = false>(options: Options<RevokeApiKeyData, ThrowOnError>) => (options.client ?? client).delete<RevokeApiKeyResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/organization/api-keys/{key_id}',
    ...options
});

/**
 * Get mode configuration
 */
export const getOrgMode = <ThrowOnError extends boolean = false>(options: Options<GetOrgModeData, ThrowOnError>) => (options.client ?? client).get<GetOrgModeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/organization/mode',
    ...options
});

/**
 * Update mode configuration
 */
export const updateOrgMode = <ThrowOnError extends boolean = false>(options: Options<UpdateOrgModeData, ThrowOnError>) => (options.client ?? client).put<UpdateOrgModeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/organization/mode',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List plans
 */
export const listPlans = <ThrowOnError extends boolean = false>(options: Options<ListPlansData, ThrowOnError>) => (options.client ?? client).get<ListPlansResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans',
    ...options
});

/**
 * Create a plan
 */
export const createPlan = <ThrowOnError extends boolean = false>(options: Options<CreatePlanData, ThrowOnError>) => (options.client ?? client).post<CreatePlanResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Copy plans from one mode to another
 */
export const copyPlans = <ThrowOnError extends boolean = false>(options: Options<CopyPlansData, ThrowOnError>) => (options.client ?? client).post<CopyPlansResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans/copy',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Archive a plan
 */
export const archivePlan = <ThrowOnError extends boolean = false>(options: Options<ArchivePlanData, ThrowOnError>) => (options.client ?? client).delete<ArchivePlanResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans/{slug}',
    ...options
});

/**
 * Get a plan by slug
 */
export const getPlan = <ThrowOnError extends boolean = false>(options: Options<GetPlanData, ThrowOnError>) => (options.client ?? client).get<GetPlanResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans/{slug}',
    ...options
});

/**
 * Update a plan
 */
export const updatePlan = <ThrowOnError extends boolean = false>(options: Options<UpdatePlanData, ThrowOnError>) => (options.client ?? client).put<UpdatePlanResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a feature on a plan
 */
export const createFeature = <ThrowOnError extends boolean = false>(options: Options<CreateFeatureData, ThrowOnError>) => (options.client ?? client).post<CreateFeatureResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans/{slug}/features',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a feature
 */
export const deleteFeature = <ThrowOnError extends boolean = false>(options: Options<DeleteFeatureData, ThrowOnError>) => (options.client ?? client).delete<DeleteFeatureResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans/{slug}/features/{feature_slug}',
    ...options
});

/**
 * Update a feature
 */
export const updateFeature = <ThrowOnError extends boolean = false>(options: Options<UpdateFeatureData, ThrowOnError>) => (options.client ?? client).put<UpdateFeatureResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans/{slug}/features/{feature_slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List active plans for an organization
 */
export const listPricing = <ThrowOnError extends boolean = false>(options: Options<ListPricingData, ThrowOnError>) => (options.client ?? client).get<ListPricingResponses, unknown, ThrowOnError>({ url: '/v1/pricing/{org_slug}', ...options });

/**
 * Cancel subscription at end of period
 */
export const cancelSubscription = <ThrowOnError extends boolean = false>(options?: Options<CancelSubscriptionData, ThrowOnError>) => (options?.client ?? client).delete<CancelSubscriptionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription',
    ...options
});

/**
 * Get my active subscription
 */
export const getMySubscription = <ThrowOnError extends boolean = false>(options?: Options<GetMySubscriptionData, ThrowOnError>) => (options?.client ?? client).get<GetMySubscriptionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription',
    ...options
});

/**
 * Subscribe to a plan (handles x402 payment)
 */
export const subscribe = <ThrowOnError extends boolean = false>(options: Options<SubscribeData, ThrowOnError>) => (options.client ?? client).post<SubscribeResponses, SubscribeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Switch to a different plan
 */
export const switchPlan = <ThrowOnError extends boolean = false>(options: Options<SwitchPlanData, ThrowOnError>) => (options.client ?? client).put<SwitchPlanResponses, SwitchPlanErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get my credit balance
 */
export const getMyCredits = <ThrowOnError extends boolean = false>(options?: Options<GetMyCreditsData, ThrowOnError>) => (options?.client ?? client).get<GetMyCreditsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription/credits',
    ...options
});

/**
 * List my invoices
 */
export const listMyInvoices = <ThrowOnError extends boolean = false>(options?: Options<ListMyInvoicesData, ThrowOnError>) => (options?.client ?? client).get<ListMyInvoicesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription/invoices',
    ...options
});

/**
 * Pay an invoice
 */
export const payInvoice = <ThrowOnError extends boolean = false>(options: Options<PayInvoiceData, ThrowOnError>) => (options.client ?? client).post<PayInvoiceResponses, PayInvoiceErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription/invoices/{id}/pay',
    ...options
});

/**
 * Resume a cancelled subscription
 */
export const resumeSubscription = <ThrowOnError extends boolean = false>(options?: Options<ResumeSubscriptionData, ThrowOnError>) => (options?.client ?? client).post<ResumeSubscriptionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription/resume',
    ...options
});

/**
 * List subscriptions
 */
export const listSubscriptions = <ThrowOnError extends boolean = false>(options: Options<ListSubscriptionsData, ThrowOnError>) => (options.client ?? client).get<ListSubscriptionsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/subscriptions',
    ...options
});

/**
 * Create a subscription (admin)
 */
export const createSubscriptionAdmin = <ThrowOnError extends boolean = false>(options: Options<CreateSubscriptionAdminData, ThrowOnError>) => (options.client ?? client).post<CreateSubscriptionAdminResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/subscriptions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Cancel a subscription (admin)
 */
export const cancelSubscriptionAdmin = <ThrowOnError extends boolean = false>(options: Options<CancelSubscriptionAdminData, ThrowOnError>) => (options.client ?? client).delete<CancelSubscriptionAdminResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/subscriptions/{id}',
    ...options
});

/**
 * Get a subscription by ID
 */
export const getSubscription = <ThrowOnError extends boolean = false>(options: Options<GetSubscriptionData, ThrowOnError>) => (options.client ?? client).get<GetSubscriptionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/subscriptions/{id}',
    ...options
});

/**
 * Track feature usage
 */
export const trackUsage = <ThrowOnError extends boolean = false>(options: Options<TrackUsageData, ThrowOnError>) => (options.client ?? client).post<TrackUsageResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/track',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List usage events
 */
export const listUsageEvents = <ThrowOnError extends boolean = false>(options?: Options<ListUsageEventsData, ThrowOnError>) => (options?.client ?? client).get<ListUsageEventsResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/usage',
    ...options
});
