// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ArchivePlanData, ArchivePlanResponses, CancelSubscriptionData, CancelSubscriptionResponses, CheckUsageData, CheckUsageResponses, CreateFeatureData, CreateFeatureResponses, CreatePlanData, CreatePlanResponses, CreateSubscriptionAdminData, CreateSubscriptionAdminResponses, GetMySubscriptionData, GetMySubscriptionResponses, GetPlanData, GetPlanResponses, ListInvoicesData, ListInvoicesResponses, ListPlansData, ListPlansResponses, ListPricingData, ListPricingResponses, ListSubscriptionsData, ListSubscriptionsResponses, ResumeSubscriptionData, ResumeSubscriptionResponses, SignInWithWalletData, SignInWithWalletResponses, SubscribeData, SubscribeErrors, SubscribeResponses, SwitchPlanData, SwitchPlanResponses, TrackUsageData, TrackUsageResponses, UpdatePlanData, UpdatePlanResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Authenticate with SIWE and get a session JWT
 */
export const signInWithWallet = <ThrowOnError extends boolean = false>(options?: Options<SignInWithWalletData, ThrowOnError>) => (options?.client ?? client).post<SignInWithWalletResponses, unknown, ThrowOnError>({ url: '/v1/auth/siwe', ...options });

/**
 * Check if a wallet can use a feature
 */
export const checkUsage = <ThrowOnError extends boolean = false>(options: Options<CheckUsageData, ThrowOnError>) => (options.client ?? client).get<CheckUsageResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/check',
    ...options
});

/**
 * List invoices
 */
export const listInvoices = <ThrowOnError extends boolean = false>(options: Options<ListInvoicesData, ThrowOnError>) => (options.client ?? client).get<ListInvoicesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/invoices',
    ...options
});

/**
 * List plans
 */
export const listPlans = <ThrowOnError extends boolean = false>(options: Options<ListPlansData, ThrowOnError>) => (options.client ?? client).get<ListPlansResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans',
    ...options
});

/**
 * Create a plan
 */
export const createPlan = <ThrowOnError extends boolean = false>(options: Options<CreatePlanData, ThrowOnError>) => (options.client ?? client).post<CreatePlanResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Archive a plan
 */
export const archivePlan = <ThrowOnError extends boolean = false>(options: Options<ArchivePlanData, ThrowOnError>) => (options.client ?? client).delete<ArchivePlanResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans/{slug}',
    ...options
});

/**
 * Get a plan by slug
 */
export const getPlan = <ThrowOnError extends boolean = false>(options: Options<GetPlanData, ThrowOnError>) => (options.client ?? client).get<GetPlanResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans/{slug}',
    ...options
});

/**
 * Update a plan
 */
export const updatePlan = <ThrowOnError extends boolean = false>(options: Options<UpdatePlanData, ThrowOnError>) => (options.client ?? client).put<UpdatePlanResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a feature on a plan
 */
export const createFeature = <ThrowOnError extends boolean = false>(options: Options<CreateFeatureData, ThrowOnError>) => (options.client ?? client).post<CreateFeatureResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/plans/{slug}/features',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List active plans for an organization
 */
export const listPricing = <ThrowOnError extends boolean = false>(options: Options<ListPricingData, ThrowOnError>) => (options.client ?? client).get<ListPricingResponses, unknown, ThrowOnError>({ url: '/v1/pricing/{org_slug}', ...options });

/**
 * Cancel subscription at end of period
 */
export const cancelSubscription = <ThrowOnError extends boolean = false>(options?: Options<CancelSubscriptionData, ThrowOnError>) => (options?.client ?? client).delete<CancelSubscriptionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription',
    ...options
});

/**
 * Get my active subscription
 */
export const getMySubscription = <ThrowOnError extends boolean = false>(options?: Options<GetMySubscriptionData, ThrowOnError>) => (options?.client ?? client).get<GetMySubscriptionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription',
    ...options
});

/**
 * Subscribe to a plan (handles x402 payment)
 */
export const subscribe = <ThrowOnError extends boolean = false>(options: Options<SubscribeData, ThrowOnError>) => (options.client ?? client).post<SubscribeResponses, SubscribeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Switch to a different plan
 */
export const switchPlan = <ThrowOnError extends boolean = false>(options: Options<SwitchPlanData, ThrowOnError>) => (options.client ?? client).put<SwitchPlanResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Resume a cancelled subscription
 */
export const resumeSubscription = <ThrowOnError extends boolean = false>(options?: Options<ResumeSubscriptionData, ThrowOnError>) => (options?.client ?? client).post<ResumeSubscriptionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/subscription/resume',
    ...options
});

/**
 * List subscriptions
 */
export const listSubscriptions = <ThrowOnError extends boolean = false>(options: Options<ListSubscriptionsData, ThrowOnError>) => (options.client ?? client).get<ListSubscriptionsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/subscriptions',
    ...options
});

/**
 * Create a subscription (admin)
 */
export const createSubscriptionAdmin = <ThrowOnError extends boolean = false>(options: Options<CreateSubscriptionAdminData, ThrowOnError>) => (options.client ?? client).post<CreateSubscriptionAdminResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/subscriptions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Track feature usage
 */
export const trackUsage = <ThrowOnError extends boolean = false>(options: Options<TrackUsageData, ThrowOnError>) => (options.client ?? client).post<TrackUsageResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/v1/track',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
