// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:9000' | 'https://api.rollover.dev' | (string & {});
};

export type Error = {
    code: string;
    message: string;
};

export type Feature = {
    credit_cost?: number;
    feature_slug: string;
    id?: string;
    limit_amount?: number;
    name: string;
    overage_price?: string;
    plan_id?: string;
    reset_period?: 'billing_cycle' | 'daily' | 'weekly' | 'monthly';
    weight?: string;
};

export type Invoice = {
    base_amount?: string;
    created_at?: string;
    id?: string;
    overage_amount?: string;
    period_end?: string;
    period_start?: string;
    settled_at?: string;
    status?: string;
    subscription_id?: string;
    total_amount?: string;
    tx_hash?: string;
    wallet_address?: string;
};

export type Plan = {
    billing_period: 'monthly' | 'yearly';
    created_at?: string;
    description?: string;
    features?: Array<Feature>;
    id: string;
    is_active?: boolean;
    last_subscribed_at?: string;
    metadata?: {
        [key: string]: unknown;
    };
    mode?: 'test' | 'live';
    name: string;
    price_usdc: string;
    setup_fee_usdc?: string;
    slug: string;
    sort_order?: number;
    subscribers?: number;
    trial_days?: number;
    updated_at?: string;
};

export type Subscription = {
    cancel_at_end?: boolean;
    created_at?: string;
    id?: string;
    mode?: string;
    org_id?: string;
    period_end?: string;
    period_start?: string;
    plan_id?: string;
    plan_name?: string;
    status?: 'active' | 'trialing' | 'expired';
    trial_end?: string;
    updated_at?: string;
    wallet_address?: string;
};

export type SignInWithWalletData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/siwe';
};

export type SignInWithWalletResponses = {
    /**
     * Session token
     */
    200: {
        expires_at?: string;
        token?: string;
        wallet?: string;
    };
};

export type SignInWithWalletResponse = SignInWithWalletResponses[keyof SignInWithWalletResponses];

export type CheckUsageData = {
    body?: never;
    path?: never;
    query: {
        wallet: string;
        feature: string;
    };
    url: '/v1/check';
};

export type CheckUsageResponses = {
    /**
     * Usage check result
     */
    200: {
        allowed: boolean;
        limit?: number;
        remaining?: number;
        used?: number;
    };
};

export type CheckUsageResponse = CheckUsageResponses[keyof CheckUsageResponses];

export type ListInvoicesData = {
    body?: never;
    path?: never;
    query: {
        slug: string;
        mode?: 'test' | 'live';
        limit?: number;
        offset?: number;
        wallet?: string;
        status?: string;
    };
    url: '/v1/invoices';
};

export type ListInvoicesResponses = {
    /**
     * Invoices
     */
    200: {
        data?: Array<Invoice>;
        limit?: number;
        offset?: number;
        total?: number;
    };
};

export type ListInvoicesResponse = ListInvoicesResponses[keyof ListInvoicesResponses];

export type ListPlansData = {
    body?: never;
    path?: never;
    query: {
        slug: string;
        mode?: 'test' | 'live';
        limit?: number;
        offset?: number;
    };
    url: '/v1/plans';
};

export type ListPlansResponses = {
    /**
     * Plans
     */
    200: {
        data?: Array<Plan>;
        limit?: number;
        offset?: number;
        total?: number;
    };
};

export type ListPlansResponse = ListPlansResponses[keyof ListPlansResponses];

export type CreatePlanData = {
    body: Plan;
    path?: never;
    query: {
        slug: string;
        mode?: 'test' | 'live';
    };
    url: '/v1/plans';
};

export type CreatePlanResponses = {
    /**
     * Created plan
     */
    201: Plan;
};

export type CreatePlanResponse = CreatePlanResponses[keyof CreatePlanResponses];

export type ArchivePlanData = {
    body?: never;
    path: {
        slug: string;
    };
    query: {
        slug: string;
        mode?: 'test' | 'live';
    };
    url: '/v1/plans/{slug}';
};

export type ArchivePlanResponses = {
    /**
     * Archived
     */
    204: void;
};

export type ArchivePlanResponse = ArchivePlanResponses[keyof ArchivePlanResponses];

export type GetPlanData = {
    body?: never;
    path: {
        slug: string;
    };
    query: {
        slug: string;
        mode?: 'test' | 'live';
    };
    url: '/v1/plans/{slug}';
};

export type GetPlanResponses = {
    /**
     * Plan
     */
    200: Plan;
};

export type GetPlanResponse = GetPlanResponses[keyof GetPlanResponses];

export type UpdatePlanData = {
    body: Plan;
    path: {
        slug: string;
    };
    query: {
        slug: string;
        mode?: 'test' | 'live';
    };
    url: '/v1/plans/{slug}';
};

export type UpdatePlanResponses = {
    /**
     * Updated plan
     */
    200: Plan;
};

export type UpdatePlanResponse = UpdatePlanResponses[keyof UpdatePlanResponses];

export type CreateFeatureData = {
    body: Feature;
    path: {
        slug: string;
    };
    query: {
        slug: string;
        mode?: 'test' | 'live';
    };
    url: '/v1/plans/{slug}/features';
};

export type CreateFeatureResponses = {
    /**
     * Created feature
     */
    201: Feature;
};

export type CreateFeatureResponse = CreateFeatureResponses[keyof CreateFeatureResponses];

export type ListPricingData = {
    body?: never;
    path: {
        org_slug: string;
    };
    query?: {
        mode?: 'test' | 'live';
    };
    url: '/v1/pricing/{org_slug}';
};

export type ListPricingResponses = {
    /**
     * Plans
     */
    200: Array<Plan>;
};

export type ListPricingResponse = ListPricingResponses[keyof ListPricingResponses];

export type CancelSubscriptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/subscription';
};

export type CancelSubscriptionResponses = {
    /**
     * Cancelled
     */
    200: Subscription;
};

export type CancelSubscriptionResponse = CancelSubscriptionResponses[keyof CancelSubscriptionResponses];

export type GetMySubscriptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/subscription';
};

export type GetMySubscriptionResponses = {
    /**
     * Subscription
     */
    200: Subscription;
};

export type GetMySubscriptionResponse = GetMySubscriptionResponses[keyof GetMySubscriptionResponses];

export type SubscribeData = {
    body: {
        org_slug: string;
        plan_slug: string;
    };
    path?: never;
    query?: never;
    url: '/v1/subscription';
};

export type SubscribeErrors = {
    /**
     * Payment required
     */
    402: unknown;
};

export type SubscribeResponses = {
    /**
     * Subscribed
     */
    201: Subscription;
};

export type SubscribeResponse = SubscribeResponses[keyof SubscribeResponses];

export type SwitchPlanData = {
    body: {
        plan_slug: string;
    };
    path?: never;
    query?: never;
    url: '/v1/subscription';
};

export type SwitchPlanResponses = {
    /**
     * Switched
     */
    200: Subscription;
};

export type SwitchPlanResponse = SwitchPlanResponses[keyof SwitchPlanResponses];

export type ResumeSubscriptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/subscription/resume';
};

export type ResumeSubscriptionResponses = {
    /**
     * Resumed
     */
    200: Subscription;
};

export type ResumeSubscriptionResponse = ResumeSubscriptionResponses[keyof ResumeSubscriptionResponses];

export type ListSubscriptionsData = {
    body?: never;
    path?: never;
    query: {
        slug: string;
        mode?: 'test' | 'live';
        limit?: number;
        offset?: number;
        status?: 'active' | 'trialing' | 'expired';
        wallet?: string;
        plan_id?: string;
    };
    url: '/v1/subscriptions';
};

export type ListSubscriptionsResponses = {
    /**
     * Subscriptions
     */
    200: {
        data?: Array<Subscription>;
        limit?: number;
        offset?: number;
        total?: number;
    };
};

export type ListSubscriptionsResponse = ListSubscriptionsResponses[keyof ListSubscriptionsResponses];

export type CreateSubscriptionAdminData = {
    body: {
        plan_slug: string;
        wallet_address: string;
    };
    path?: never;
    query: {
        slug: string;
        mode?: 'test' | 'live';
    };
    url: '/v1/subscriptions';
};

export type CreateSubscriptionAdminResponses = {
    /**
     * Created subscription
     */
    201: Subscription;
};

export type CreateSubscriptionAdminResponse = CreateSubscriptionAdminResponses[keyof CreateSubscriptionAdminResponses];

export type TrackUsageData = {
    body: {
        /**
         * Usage amount
         */
        amount: number;
        /**
         * Feature slug
         */
        feature: string;
        /**
         * Wallet address (0x...)
         */
        wallet: string;
    };
    path?: never;
    query?: never;
    url: '/v1/track';
};

export type TrackUsageResponses = {
    /**
     * Usage tracked
     */
    200: {
        ok?: boolean;
    };
};

export type TrackUsageResponse = TrackUsageResponses[keyof TrackUsageResponses];
